export const catchError = e => {
  throw new Error(e)
}
